import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import Theme from "./Theme";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/ar.ico" sizes="any" />
      </head>
      <body className={`bg-background text-foreground ${inter.className}`}>
        <Theme>
          <div className="px-4 md:px-0 md:w-[70%] lg:w-[55%] xl:w-[35%] mx-auto">
            <Header />
            {children}
          </div>
        </Theme>
      </body>
    </html>
  );
}
