import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="icon" href="/ar.ico" sizes="any" />
      </head>
      <body className="dark-mode">
        <div className="px-10 md:px-0 md:w-[60%] lg:w-[50%] xl:w-[35%] mx-auto">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
